# Generated by Django 3.2.25 on 2025-10-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermitBasic',
            fields=[
                ('permit_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '许可证基础信息',
                'db_table': 'sy_permit_basic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentralDirector',
            fields=[
                ('permit', models.OneToOneField(db_column='permit_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='approvals.permitbasic')),
                ('chief_inspector', models.CharField(max_length=50)),
                ('approval_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '中心平台-总监批准',
                'db_table': 'sy_approval_central_director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentralManage',
            fields=[
                ('permit', models.OneToOneField(db_column='permit_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='approvals.permitbasic')),
                ('manage_supervision', models.CharField(max_length=50)),
                ('approval_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '中心平台-主管审核',
                'db_table': 'sy_approval_central_manage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentralReview',
            fields=[
                ('permit', models.OneToOneField(db_column='permit_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='approvals.permitbasic')),
                ('assignment_supervisor', models.CharField(max_length=50)),
                ('approval_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '中心平台-审查',
                'db_table': 'sy_approval_central_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentralSafety',
            fields=[
                ('permit', models.OneToOneField(db_column='permit_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='approvals.permitbasic')),
                ('safety_supervision', models.CharField(max_length=50)),
                ('approval_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '中心平台-安全审核',
                'db_table': 'sy_approval_central_safety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellheadDirector',
            fields=[
                ('permit', models.OneToOneField(db_column='permit_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='approvals.permitbasic')),
                ('chief_inspector', models.CharField(max_length=50)),
                ('approval_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '井口平台-批准',
                'db_table': 'sy_approval_wellhead_director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WellheadReview',
            fields=[
                ('permit', models.OneToOneField(db_column='permit_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='approvals.permitbasic')),
                ('assignment_supervisor', models.CharField(max_length=50)),
                ('approval_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '井口平台-审查',
                'db_table': 'sy_approval_wellhead_review',
                'managed': False,
            },
        ),
    ]
